### ISSUE TITLE
How to push arguments

### ISSUE THREAD

**Issue by km147** [WilsonDhChen/mediasrv_linux#1]
In Linux how to push arguments that specifies frame rate and audio sample rate etc
e.g. mediaserv [http://input-url]  output-fps audio-sample-rate audio-format buffer-size video-format max-bit-rate min-bit-rate [rtmp://output-url]

**Comment by WilsonDhChen** [comment]
these arguments the mediasrv is not needed.  and the arguments is used in Video/Audio encoder then push to mediasrv throungh RTMP protocol

**Comment by WilsonDhChen** [comment]
all the arguments in RTMP protocol
